### ISSUE TITLE
Support source data from query string

### ISSUE THREAD

**Issue by ntrrg** [TomWright/daselplayground#7]
Hi! I think it would be useful if one could send data through the URL, e.g. https://dasel.tomwright.me/?src=%7B%0A%20%20%22name%22%3A%20%22Tom%22%0A%7D

**Comment by TomWright** [comment]
Are you looking to use this as some form of API? Or as a helper to pre-load some details into the form?

I'm happy to support some kind of `in` and `cmd` query parameters.

**Comment by ntrrg** [comment]
Yeah, for populating the form. I was thinking it would be a great visualization tool for some automated workflows

**Comment by TomWright** [comment]
Great point! I'll add this to the to-do list 👍

**Comment by ntrrg** [comment]
Cool, I am not a big fan of JavaScript building tools, but I will give it a try and let you know how it goes :smile:

**Comment by TomWright** [comment]
If you want to, feel free! If not I can work on it in the next couple of days 🙂

**Comment by TomWright** [comment]
@ntrrg This has been released with `v0.3.10`.

I can't push it to production yet because there are ongoing issues with github actions. I will deploy this tomorrow

**Comment by ntrrg** [comment]
That is fine :) thanks for your work!

**Comment by TomWright** [comment]
It's released now 🙂
