### ISSUE TITLE
Playground broken

### ISSUE THREAD

**Issue by franz-josef-kaiser** [TomWright/daselplayground#9]
Hi Tom, first: Thanks a lot for your package.

Sadly the [playground](https://dasel.tomwright.me/) currently is broken and not even the most [basic example](https://daseldocs.tomwright.me/functions/string) does work.

Argument
```
-r json 'string(my string)'
```

Input
```
{}
```

Error
```
Error: exit status 1: Error: could not query node: could not find value: no value found for selector: string(my string): map[]
```

**Comment by TomWright** [comment]
Hey @franz-josef-kaiser ,

Thanks for raising an issue. I think I just need to update the dasel version available on the playground.

I completely forgot to keep it updated as new dasel versions get released but I'll get on this tomorrow

**Comment by TomWright** [comment]
Hey @franz-josef-kaiser, I've just fixed this. See https://dasel.tomwright.me/s/65dd0207-8966-4bd9-acfa-a1f7c374ddf2 for a working example.

**Comment by franz-josef-kaiser** [comment]
Thanks @TomWright !
